env:
  global:
    - QUIET=0
  matrix:
    - BRANCH=master
    - BRANCH=master DOCKER_STORAGE_DRIVER=aufs
    - BRANCH=master DOCKER_STORAGE_DRIVER=devicemapper
    - BRANCH=master DOCKER_STORAGE_DRIVER=btrfs

sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run docker info
  - ./run docker run busybox date
  - ./run docker-compose build
  - ./run docker-compose run aaa date
