env:
  global:
    - QUIET=0
    - UML_FIG=0
    - UML_DOCKERCOMPOSE=1
  matrix:
    - BRANCH=v1.0.0
    - BRANCH=stable
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=aufs
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=devicemapper
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=vfs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=devicemapper
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=vfs

    # same as above with version 1.6.2
    - BRANCH=v1.0.0                                                                DOCKER_VERSION=1.6.2
    - BRANCH=stable                                                                DOCKER_VERSION=1.6.2
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=aufs            DOCKER_VERSION=1.6.2
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=devicemapper    DOCKER_VERSION=1.6.2
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=vfs             DOCKER_VERSION=1.6.2
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=devicemapper    DOCKER_VERSION=1.6.2
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=vfs             DOCKER_VERSION=1.6.2

    # same as above with version from get.docker.com
    - BRANCH=v1.0.0                                                                DOCKER_VERSION=get.docker.com
    - BRANCH=stable                                                                DOCKER_VERSION=get.docker.com
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=aufs            DOCKER_VERSION=get.docker.com
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=devicemapper    DOCKER_VERSION=get.docker.com
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=vfs             DOCKER_VERSION=get.docker.com
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=devicemapper    DOCKER_VERSION=get.docker.com
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=vfs             DOCKER_VERSION=get.docker.com

    # broken matrix
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=btrfs
    - BRANCH=develop DOCKER_BACKEND_FS=tmpfs DOCKER_STORAGE_DRIVER=overlay
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=aufs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=btrfs
    - BRANCH=develop DOCKER_BACKEND_FS=host  DOCKER_STORAGE_DRIVER=overlay



sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - df -h
  - ./run docker info
  - ./run docker run busybox date
  - ./run docker-compose build
  - ./run docker-compose run aaa date
  - ./run docker info
  - df -h
